Add pipeline to automatically zip assets for release
Mojang/bedrock-samples pull request #4
Opened 2022-11-03 17:40 UTC by GTB3NW

2022-11-08 14:54 UTC, DaanV2 requested changes

2022-11-09 10:09 UTC, DaanV2 approved these changes

2022-11-12 22:14 UTC, JaylyDev approved these changes

2022-11-15 22:12 UTC, GTB3NW commented
Spoke to Mike about this, he'd prefer to continue manually and improve automation in house

2022-11-15 22:12 UTC, closed without merging